Update Dockerfile

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -28,9 +28,11 @@ RUN curl -o /usr/local/bin/openvpn-install.sh https://raw.githubusercontent.com/
     chmod +x /usr/local/bin/openvpn-install.sh
 
 # 下载 frpc 最新版本并验证下载
-RUN wget https://github.com/fatedier/frp/releases/download/v0.61.2/frp_0.61.2_linux_amd64.tar.gz -O /tmp/frpc.tar.gz && \
+RUN wget https://github.com/fatedier/frp/releases/download/v0.61.2/frp_0.61.2_linux_amd64.tar.gz -O /tmp/frpc.tar.gz || \
+    (echo "Failed to download frpc"; exit 1) && \
     ls -lh /tmp && \
-    tar -xzvf /tmp/frpc.tar.gz -C /tmp && \
+    tar -xzvf /tmp/frpc.tar.gz -C /tmp || \
+    (echo "Failed to extract frpc"; exit 1) && \
     ls -lh /tmp && \
     mv /tmp/frpc /usr/local/bin/frpc && \
     chmod +x /usr/local/bin/frpc
